# permissions for end users to view ipleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iplease-viewer-role
rules:
- apiGroups:
  - ipam.routerd.net
  resources:
  - ipleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.routerd.net
  resources:
  - ipleases/status
  verbs:
  - get
