# permissions for end users to edit ipleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iplease-editor-role
rules:
- apiGroups:
  - ipam.routerd.net
  resources:
  - ipleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.routerd.net
  resources:
  - ipleases/status
  verbs:
  - get
