# permissions for end users to view ippools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ippool-viewer-role
rules:
- apiGroups:
  - ipam.routerd.net
  resources:
  - ippools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.routerd.net
  resources:
  - ippools/status
  verbs:
  - get
